### ISSUE TITLE
Tokenize only newly calculated attributes not the whole project

### ISSUE THREAD

**Issue by FelixKirsch** [code-kern-ai/refinery-ac-exec-env#4]
After calculating a new attribute the whole project is tokenized again.
This is not needed as the old attributes are unchanged and it would be sufficient to only tokenize the new attribute and add the token to the docbins and the record_tokenized table.

Issue in tokenizer:
https://github.com/code-kern-ai/refinery-tokenizer/issues/7

**Comment by JWittmeyer** [comment]
included in pr https://github.com/code-kern-ai/refinery-tokenizer/pull/17
